### ISSUE TITLE
TZ does not affect time

### ISSUE THREAD

**Issue by ghost** [JAremko/docker-emacs#10]
First of all, thank so much for creating this image!

However, today I noticed something weird about it.

(I'm running Docker on macos.)

When I set the TZ for the image, it doesn't affect the actual time.

So, for example, the time on my Mac is 11:07 AM America/Los_Angeles, and here is what I tried (for the second attempt, I set the TZ):

```
$ docker run -ti --rm -e UNAME="emacser" -e GNAME="emacsers" -e UID="1000" -e GID="1000" jare/emacs:latest /bin/bash

emacser@9ee3674439e7:/mnt/workspace$ date
Mon Jun  4 18:07:08 UTC 2018

emacser@9ee3674439e7:/mnt/workspace$ exit
exit

[mmello@mmello-mb:~ ]
$ docker run -ti --rm -e UNAME="emacser" -e TZ=America/Los_Angeles -e GNAME="emacsers" -e UID="1000" -e GID="1000" jare/emacs:latest /bin/bash

emacser@c3e2766a83a6:/mnt/workspace$ date
Mon Jun  4 18:08:33 America 2018

```

So, as you can see, it is reporting the correct TZ, but the time is not affected!

Any idea how to deal with this?  I tried googling, but got nowhere.

I want it to report the date as `Mon Jun  4 11:08:33 America 2018`.

Thanks!

**Comment by JAremko** [comment]
~@matt812 I think [`su-exec`](https://github.com/JAremko/docker-emacs/blob/master/asEnvUser#L44) doesn't pass it down. I can fix this issue. Meanwhile something like  `docker run -ti --rm -e UNAME="emacser"  -e GNAME="emacsers" -e UID="1000" -e GID="1000" jare/emacs:latest  TZ=America/Los_Angeles /bin/bash`  may work.~

 - - - - - 

Oh wait. I misunderstood your issue. Hmm.

**Comment by JAremko** [comment]
@matt812 you can try  `docker run -ti --rm -e UNAME="emacser" -e TZ=America/Los_Angeles -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro  -e GNAME="emacsers" -e UID="1000" -e GID="1000" jare/emacs:latest /bin/bash`  

But it may not work.  See`https://github.com/docker/for-mac/issues/2396`

**Comment by ghost** [comment]
@JAremko , what worked for me was this:


mkdir ~/etc
cp /etc/localtime ~/etc/
docker run -ti --rm -e UNAME="emacser" -e TERM=xterm-256color -e GNAME="emacsers" -e UID="1000" -e GID="1000" -v ~/.emacs.d:/home/emacs/.emacs.d -v ~/.ssh:/home/emacs/.ssh **-v ~/etc/localtime:/etc/localtime** jare/emacs:latest /bin/bash


Thanks!

**Comment by JAremko** [comment]
@matt812  Glad it works :+1:
