### ISSUE TITLE
Docs says "latest" = "dockerfiles/emacs26", but latest is still 25.3

### ISSUE THREAD

**Issue by ghost** [JAremko/docker-emacs#11]
The readme says that #latest is emacs26, but I am seeing that it is 25.3, still.

Can you deploy to dockerhub?

Thanks!

**Comment by JAremko** [comment]
@matt812  I think it should be ok now.

![https://i.imgur.com/5SlWSAk.png](https://i.imgur.com/5SlWSAk.png)
