### ISSUE TITLE
Difference with Silex/docker-emacs

### ISSUE THREAD

**Issue by Silex** [JAremko/docker-emacs#12]
Hello!

I run https://github.com/Silex/docker-emacs and I just discovered this repo.

Can you elaborate a bit on the differences between these repositories? That way I can mention you on the README.

Given the projects looks very similar and the differences are mainly on the README, maybe I could add you as a collaborator and we merge your usage recommandations/tips and tricks there?

I'm currently on holidays so take your time to think it through, there's no rush :-)

**Comment by Silex** [comment]
@JAremko: friendly ping

**Comment by JAremko** [comment]
@Silex  friendly pong.

> Given the projects looks very similar and the differences are mainly on the README, maybe I could add you as a collaborator and we merge your usage recommandations/tips and tricks there?

No problem. 

> Can you elaborate a bit on the differences between these repositories? That way I can mention you on the README.

Well.. it has [this script](https://github.com/JAremko/docker-emacs/blob/master/asEnvUser).  I mainly use those dockerfiles as a base for Spacemacs CI tests and [spacemacs-docker](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bdistributions/spacemacs-docker)

**Comment by Silex** [comment]
@JAremko: ah right, the use cases are different. Thanks for the information!

I think merging the two would result in one project bending more than necessary, thus it's probably best if they stay separate for now.

If it makes sense for you, you might consider using `FROM silex/emacs:$VERSION` in your Dockerfiles. Anyway I'll mention you in the alternative section :wink:
