### ISSUE TITLE
Try Alpine to make image smaller

### ISSUE THREAD

**Issue by kenkangxgwe** [JAremko/docker-emacs#14]
Currently, my final built docker image for takes about 750Mb, without other dependencies installed. Shall we try using Alpine (instead of Ubuntu) to see if we can reduce the size? Of course, git or other dev tools need to be installed manually as the tradeoff.

**Comment by JAremko** [comment]
@kenkangxgwe  there is an alpine image `jare/emacs:alpine`

**Comment by kenkangxgwe** [comment]
Oh, I see. I came from your `spacemacs` docker image, and did not see there is an `emacs:alpine` in this repo.
Thank you
