### ISSUE TITLE
trouble connecting through xpra in windows.

### ISSUE THREAD

**Issue by ninrod** [JAremko/docker-emacs#2]
Jaremko, I'm having trouble connecting through xpra in windows. 

I have docker running in a local vagrant machine in a windows box. I started the container and bound port `8888:8888` with: 

`docker run -ti --rm -v ~/.ssh/pub_rsa:/etc/pub-keys/my.pub -p 8888:8888 docker.io/jare/spacemacs-docker:latest`. Here is the output: 

```shell
jaremko λ ./xprarun.sh
Starting in the standard mode...

Warning: running as root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.13.0-95-generic x86_64 Ubuntu
Current Operating System: Linux 712c15a4199f 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-327.22.2.el7.x86_64 root=/dev/mapper/vg_vagrantcentos-lv_root ro crashkernel=auto rd.lvm.lv=vg_vagrantcentos/lv_root r$.lvm.lv=vg_vagrantcentos/lv_swap rhgb quiet LANG=en_US.UTF-8
Build Date: 14 September 2016  03:33:24PM
xorg-server 2:1.18.4-0ubuntu0.1 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.log", Time: Wed Nov  9 17:24:30 2016
(++) Using config file: "/etc/xpra/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
2016-11-09 17:24:30,804 created unix domain socket: /root/.xpra/712c15a4199f-14
2016-11-09 17:24:33,717 Warning: webcam forwarding is disabled
2016-11-09 17:24:33,717  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2016-11-09 17:24:33,717  make sure that the 'v4l2loopback' kernel module is installed and loaded
2016-11-09 17:24:33,717 found 0 virtual video devices

Warning: running as root
2016-11-09 17:24:34,332 GStreamer version 1.8 for Python 2.7
2016-11-09 17:24:34,339 D-Bus notification forwarding is available
2016-11-09 17:24:34,566 started command 'sdrunemacs ' with pid 80
2016-11-09 17:24:34,567 xpra X11 version 0.17.6-r14318
2016-11-09 17:24:34,567  running with pid 28 on Linux Ubuntu 16.04 xenial
2016-11-09 17:24:34,567  on display :14
2016-11-09 17:24:34,638 xpra is ready.

(emacs:82): GLib-WARNING **: poll(2) failed due to: Operation not permitted.

(emacs:82): GLib-WARNING **: poll(2) failed due to: Operation not permitted.

(emacs:82): GLib-WARNING **: poll(2) failed due to: Operation not permitted.

(emacs:82): GLib-WARNING **: poll(2) failed due to: Operation not permitted.
```

Now I open up cygwin and try to connect to the xpra server using Xpra_cmd using this line: 

`./Xpra_cmd.exe attach --encoding=rgb --ssh="ssh -p 8888" ssh:vagrant@vagrant:14`

here is the output: 

```txt
2016-11-09 17:28:43,069 Xpra gtk2 client version 0.17.5-r13487
2016-11-09 17:28:43,071  running on Microsoft Windows 7
2016-11-09 17:28:43,401 GStreamer version 1.8 for Python 3.4
2016-11-09 17:28:43,710 OpenGL_accelerate module loaded
2016-11-09 17:28:43,717 OpenGL enabled with AMD Radeon(TM) HD8490
2016-11-09 17:28:43,829  detected keyboard: layout=us
2016-11-09 17:28:43,831  desktop size is 3360x1050 with 1 screen:
2016-11-09 17:28:43,831   Default (889x277 mm - DPI: 96x96)
2016-11-09 17:28:43,831     DISPLAY2 1680x1050 at 1680x0 (593x370 mm - DPI: 71x72) workarea: 1680x1020
2016-11-09 17:28:43,831     DISPLAY1 1680x1050 (593x370 mm - DPI: 71x72) workarea: 1680x1050
2016-11-09 17:28:43,831  upscaled by 125%, virtual screen size: 2688x840
2016-11-09 17:28:43,831   Default (889x277 mm - DPI: 76x77)
2016-11-09 17:28:43,831     DISPLAY2 1344x840 at 1344x0 (593x370 mm - DPI: 57x57) workarea: 1344x816
2016-11-09 17:28:43,831     DISPLAY1 1344x840 (593x370 mm - DPI: 57x57) workarea: 1344x840
2016-11-09 17:28:44,940 failed to receive anything, not an xpra server?
2016-11-09 17:28:44,941   could also be the wrong username, password or port
2016-11-09 17:28:44,941   or maybe this server does not support 'unknown' compression or 'bencode' packet encoding?
2016-11-09 17:28:44,941 Connection lost
```

What am I doing wrong?

**Comment by JAremko** [comment]
@ninrod  
try `docker run -ti --rm  -p 10000:10000 -e XPRA_PASSWORD=qwerty  -e SDMODE=webbrowser_insecure  docker.io/jare/docker-emacs`
and open `localhost:10000/index.html?encoding=png&password=qwerty`
If it doesn't work replace `localhost` with your VM IP.  
_This way we can determine the correct address._

Then use this address to connect. 

If it doesn't work try `docker run -ti --rm -v ~/.ssh/pub_rsa:/etc/pub-keys/my.pub -p 22:22 docker.io/jare/docker-emacs`  and connect with `./Xpra_cmd.exe attach --encoding=rgb ssh:root@<address>:14`

If you want to use custom ssh port:  `docker run -ti --rm -v ~/.ssh/pub_rsa:/etc/pub-keys/my.pub -e SSHD_PORT=8888  -p 8888:8888 docker.io/jare/docker-emacs` or  
`docker run -ti --rm -v ~/.ssh/pub_rsa:/etc/pub-keys/my.pub  -p 8888:22 docker.io/jare/docker-emacs`  
 and connect `./Xpra_cmd.exe attach --encoding=rgb --ssh="ssh -p 8888" ssh:root@<address>:14`

**Comment by JAremko** [comment]
@ninrod  now you can use https://github.com/JAremko/spacemacs-docker-seed  
We need some good testing :stuck_out_tongue:

**Comment by ninrod** [comment]
ok. this configuration worked for me on OSx: https://github.com/ninrod/docker-spacemacs-tests/blob/master/img/xprafix.png

let's see on windows when I get to work.

note: using the docker for macOS beta. (not vagrant).

**Comment by ninrod** [comment]
one thing I can say for sure: the latency is very noticeable with xpra.

with iterm2 latency is zero.

**Comment by JAremko** [comment]
@ninrod 

> one thing I can say for sure: the latency is very noticeable with xpra.
> with iterm2 latency is zero.  

Check if Xpra client complained about missing python libraries, it may be the reason.

But we can ditch Xpra or make it optional if it will be a problem.  For now I'm trying to figure out how to maximally simplify the use.  and finish the docs (now they are really crappy)

**Comment by JAremko** [comment]
I haven't tried it with the TCP option. It may be slower than ssh for some reason. Also try disabling zlib compression in the taskbar widget (if it is there) should be called something like compression level - set it to 0.  

Btw thank you very much for the testing.  :heart:

**Comment by JAremko** [comment]
@ninrod  ok I  made fresh install on Windows 7 (It's somewhat fancier than Win 10) :
1. get `PuTTYgen` http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html and convert your identity rsa to putty format.  
2. Get `Pageant`  http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html launch it and add this new putty  key.
3.  Start the server ![start](https://cloud.githubusercontent.com/assets/1898905/20196762/ded182b6-a7a4-11e6-91ef-85d0e8d4488a.png)
   ![started](https://cloud.githubusercontent.com/assets/1898905/20196813/09b13f30-a7a5-11e6-9779-7e45e9c4d536.png)
4. Connect  
   ![xpra](https://cloud.githubusercontent.com/assets/1898905/20196855/459af504-a7a5-11e6-9103-f20004bbeb1f.png)

_`192.168.99.100` is my Windows 7 docker machine IP. With Docker for Windows (Windows 10 PRO) it should be localhost_
![xpred](https://cloud.githubusercontent.com/assets/1898905/20196904/7fbf415e-a7a5-11e6-909c-01b8f86f7c3c.png)

**Comment by JAremko** [comment]
@ninrod  Connecting via GUI with lossless settings seems to be glitchy.  But this works fine 
![xpra-cons](https://cloud.githubusercontent.com/assets/1898905/20197630/327f5e02-a7a9-11e6-9818-4a290c0b72e1.png)  
 After connecting you can change quality with the Xpra widget(system tray icon, or how it is called) near the system clock.

**Can docker brigde(in the combination with all the virtualization) be too slow?** :confused:  
We should try with   `--net=host` on Windows 10 or MacOS `docker-machine ip` shoud give the address to connect.

**Comment by ninrod** [comment]
@JAremko np, happy to be of help. 

how did you manage to run docker inside mingw? are you using docker-machine?

I'm running docker inside a vagrant box running centos.

**Comment by JAremko** [comment]
@ninrod  I fixed it. 
![hurrdurr](https://cloud.githubusercontent.com/assets/1898905/20199482/6a0934e2-a7b3-11e6-9f91-d57cfca684ec.png)  

Apparently you have to use "Lowest Bandwidth". Now it does't lag. :confused:   magic

> how did you manage to run docker inside mingw? are you using docker-machine?

https://www.docker.com/products/docker-toolbox

**Comment by ninrod** [comment]
Oh! I see you're using docker machine. (having some trouble testing because my daughter is not cooperating, hehe).

**Comment by JAremko** [comment]
> having some trouble testing because my daughter is not cooperating, hehe   

@ninrod  Tell her that you are trying to set up  :candy:  :candy:   :candy:  vending machine :stuck_out_tongue:

**Comment by syl20bnr** [comment]
Following the post @JAremko gave me [1] I was able to make `spacemacs/spacemacs-docker` container to work with XQuartz on macOS using Docker for Mac.

After allowing connections from client in XQuartz and restarting it simply do in a bash shell:

``` sh
xhost
ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost + $ip
docker run -ti --network=host -e DISPLAY=$ip:0 -v /tmp/.X11-unix --entrypoint=/bin/bash -e NO_AT_BRIDGE=1 -e SHELL=/bin/bash spacemacs/spacemacs-docker
```

then `emacs` in container's shell.

Setting the entry point to bash instead of emacs allow to be able to restart emacs (SPC q R) without exiting the container.

[1] https://fredrikaverpil.github.io/2016/07/31/docker-for-mac-and-gui-applications/

**Comment by JAremko** [comment]
As @ninrod  suggested I tried cygwin xserver and fallowed this instruction http://manomarks.github.io/2015/12/03/docker-gui-windows.html  it is for Docker toolbox (I'll try it on Win 10 with Docker for Windows and write the instruction) So far I have no issues, it works really well.

I propose removing Xpra from the base image and adding it optionally (probably as a special layer for the spacemacs-docker distribution) for those who want to showcase Spacemacs via web browser and do other Xpra specific stuff.

**Comment by ninrod** [comment]
@JAremko @syl20bnr I use emacs at work in this fashion. I only have access to a windows box, so I install a cygwin xserver, virtualbox, vagrant and then I `vagrant up` from a vagrant centos box with a docker image that contains an emacs25.1 full build. Then I mount `.emacs.d` with my config. 

working very well. Only problem is that the image is reaching 3GB because I put everything and the kitchen sink in it.

**Comment by JAremko** [comment]
With Docker for Windows  (cygwin) 

```
find out *your-machine-ip* (you can use ipconfig)
export DISPLAY=*your-machine-ip*:0.0
startxwin -- -listen tcp &
xhost + *your-machine-ip*
docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --entrypoint=/bin/bash spacemacs/spacemacs-docker emacs
```

Basically the same as with Docker toolbox. But  for `docker run ... -ti ..`  you need to prefix `docker run` with mintty(wintty?)  (haven't tested)

**Comment by JAremko** [comment]
@ninrod What cygwin packages are required for this to work? I simply installed all X11 stuff :smile:

**Comment by ninrod** [comment]
@JAremko 
- You install cygwin like this (.bat) 

``` bat
setup-x86_64.exe ^
  --site http://yourfavoritecygwinmirror ^
    --no-admin ^
    --local-package-dir "D:\cygwin-local-packages" ^
    --root "D:\cygwin" ^
    --only-site ^
      -P xinit ^
      -P xorg-server ^
      -P openssh
```
- then you start the x-server like this: (those are .bat lines)

``` bat
@echo off
setlocal EnableDelayedExpansion

D:\cygwin\bin\run.exe --quote /usr/bin/bash.exe -l -c "cd; kill `ps | grep XWin | awk '{print $1}'`; /usr/bin/X :0 -multiwindow -listen tcp"
```
- then you define the IP of the host as your display in your dockerfile:

`ENV DISPLAY=10.0.2.2:0.0 NO_AT_BRIDGE=1`
- In my docker image, I install x11 like this:

`RUN yum -y group install "X Window System" "Fonts" && yum clean all`

then you proceed to the vagrant directory using mintty and just: `vagrant up && vagrant ssh`.

_note_: in my vagrantfile, I use: `config.vm.network "private_network", ip: MY_VAGRANT_IP`

then you start your container with whatever configs and bam, you can use spacemacs, intellij or just about any X enabled application. 

It's magical.

**Comment by JAremko** [comment]
@ninrod  Thanks!

**Comment by syl20bnr** [comment]
@ninrod why vagrant is necessary? Are Cygwin and Docker for Windows not enough ?

**Comment by JAremko** [comment]
@syl20bnr Docker for Windows requires at least Windows 10 PRO.  
I tested with with Windows 7 + docker toolbox + Cygwin  and Windows 10 PRO + Docker for Windows + Cygwin. Both work fine. I don't think that docker toolbox has benefits compared to Vagrant (if you know how to use it - I don't  :smile: )

**Comment by JAremko** [comment]
@ninrod  @syl20bnr  I found this tool https://github.com/matthieudelaro/nut  gotta dig into it.  It may give us "silver bullet" for all platforms or at least a hint how  to make(cast) one.

**Comment by ninrod** [comment]
@JAremko @syl20bnr there is a hidden benefit from using vagrant.

If I'm going to develop git projects inside the docker container, I will want to set the mount point from a UNIX file system, which is what vagrant gives me. 

See, with docker for windows, or toolbox, you are using the windows file system as a mount point. When you destroy your containers, where is your data? In a windows file system. And that is a major pain in the ass. Think of symlinks problems, git camelcase filename problems, permissions and whatnot. It is a nightmare. 

Vagrant protects you from that because you can git clone your repos from inside the vagrant box to a directory that is inside the vagrantbox and you mount that dir to the container you want to run. makes sense?

I don't touch windows in this workflow. I just clone everything that I need inside vagrant mount that to my containers and then I work exclusively inside the containers. 

When I destroy my containers, my data is inside the vagrantbox, in a UNIX filesystem. I then `vagrant halt` and then I can turn off my computer. When I `vagrant up` again, everything is there. Nothing stays on windows. 

vagrant gives you a `UNIX persistance layer` which protects you from the dangers of the NTFS file system.

**Comment by ninrod** [comment]
@JAremko I don't think that's the use case you are looking for for the containerized spacemacs image. I think he is trying to tackle reproducible project tooling. 

And even then I don't feel the need. My tooling is 100% docker containerized and I do everything with simple bash scripts. works wonderfully.

**Comment by JAremko** [comment]
@ninrod Looks like I also need to explore Vagrant.

This weekend will be extra fun,.. ish

**Comment by ninrod** [comment]
Well that's really only needed if you are in the awful situation of being forced to use a windows box for work, like I am. I would not use vagrant in OSx, for example. 

Maybe I'll ditch vagrant If I can have access to a windows 10 PRO box with docker for windows. But only if I can mount my stuff inside a UNIX file system through the windows 10 ubuntu thing.

**Comment by JAremko** [comment]
>  I don't think that's the use case you are looking for for the containerized spacemacs image. I think he is trying to tackle reproducible project tooling.

@ninrod  It defenetly has X11 stuff in it. And they use XQuartz  for MacOS. Don't know about Windows.   

![https://camo.githubusercontent.com/b32c086f7da89f3365062f9a6a49b7f64377cb35/687474703a2f2f692e696d6775722e636f6d2f4b6650676d72322e676966](https://camo.githubusercontent.com/b32c086f7da89f3365062f9a6a49b7f64377cb35/687474703a2f2f692e696d6775722e636f6d2f4b6650676d72322e676966)

> Maybe I'd ditch vagrant If I can have access to windows 10 PRO with docker for windows. But only if I can mount my stuff inside a UNIX file system through the windows 10 ubuntu thing.  

I heard that Ubuntu thingy (when enabled)  ruins Cygwin  :confused:

**Comment by ninrod** [comment]
Interesting. 

Jesus. I think I'll have to stay with vagrant for a long time.

**Comment by JAremko** [comment]
They also have [Chrome example](https://github.com/matthieudelaro/nut/blob/manualbuild/examples/chrome/nut.yml)  and [tensorflow](https://github.com/matthieudelaro/nut/blob/manualbuild/examples/tensorflow/nut.yml) that (probably) uses GPU 

But it seems that GUI for Windows in unimplemented. 

---

So  apparently nut has a problem with maintenance, we probably shouldn't rely on it. Also it doesn't simplify process too much and requires platform specific steps.

**Comment by JAremko** [comment]
Finally  :dagger: \  :shipit: / :hocho:   https://github.com/syl20bnr/spacemacs/pull/8588

**Comment by ninrod** [comment]
congrats @JAremko. By the way, with the advent of docker for windows 10, I have fully substituted my vagrant box solution. the only thing you need now to run emacs inside a docker container in windows is a cygwin x server and a console with access to a ssh client. much simpler.

**Comment by JAremko** [comment]
@ninrod  Thanks. I hope people will find it useful.

**Comment by JAremko** [comment]
@ninrod  btw http://stackoverflow.com/a/39188790/1224362 and recent update https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/
