### ISSUE TITLE
spacemacs-docker broken

### ISSUE THREAD

**Issue by driftcrow** [JAremko/docker-emacs#3]
you contributed spacemacs-docker layer depend on you docker-emacs image, seems you remove this image ,so it autobuild broken
[log](https://hub.docker.com/r/spacemacs/spacemacs-docker/builds/)
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

Executing build hook...
Sending build context to Docker daemon 76.29 kB


Step 1 : FROM jare/docker-emacs:latest

Pulling repository docker.io/jare/docker-emacs

Error: image jare/docker-emacs:latest not found

build hook failed! (1)
```

**Comment by JAremko** [comment]
Yeah thanks. I'm planning to scrap and rework it. Soon. :wink:

**Comment by JAremko** [comment]
Should be fixed with https://github.com/syl20bnr/spacemacs/pull/8588

**Comment by JAremko** [comment]
Ok it was merged.  We also gonna need to replace all of https://hub.docker.com/r/spacemacs/  stuff with new  `spacemacs/emacs25` autobuild from  https://github.com/syl20bnr/spacemacs/blob/develop/Dockerfile.emacs25 
 And another  autobuild `spacemacs/emacs-snapshot`from  https://github.com/syl20bnr/spacemacs/blob/develop/Dockerfile.snapshot

But only @syl20bnr  can do this so this isn't something that I can solve.
