### ISSUE TITLE
docker for windows 10 vcxsrv combo

### ISSUE THREAD

**Issue by ninrod** [JAremko/docker-emacs#8]
hi @JAremko. I ditched vagrant for windows for 10. I kind of documented my setup in this reddit thread. 

cheers.

https://www.reddit.com/r/emacs/comments/7a63r4/emacs_in_win10linuxdockerxserver_combo/

**Comment by JAremko** [comment]
@ninrod Hi :heart:

I'll add it to the README. Thx!
